import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faAngleDown,
    faAngleRight,
    faArrowUpRightFromSquare,
    faAsterisk,
    faAtom,
    faBars,
    faBoxArchive,
    faCaretLeft,
    faCaretRight,
    faChevronLeft,
    faChevronRight,
    faCloudShowersHeavy,
    faCode,
    faCube,
    faExclamationCircle,
    faExclamationTriangle,
    faFaceFrown,
    faFile,
    faFlag,
    faFolder,
    faInfoCircle,
    faLightbulb,
    faLink,
    faMagnifyingGlass,
    faSpinner,
    faXmark,
    faWrench,
} from "@fortawesome/free-solid-svg-icons";
import { faStar } from "@fortawesome/free-regular-svg-icons";
import { faGithub, faBtc } from "@fortawesome/free-brands-svg-icons";
export const brandName = [ "github", "btc" ];

library.add(
    faAngleRight,
    faAngleDown,
    faBars,
    faMagnifyingGlass,
    faCaretRight,
    faCaretLeft,
    faXmark,
    faFile,
    faFolder,
    faFaceFrown,
    faAsterisk,
    faCube,
    faLightbulb,
    faInfoCircle,
    faExclamationCircle,
    faExclamationTriangle,
    faLink,
    faArrowUpRightFromSquare,
    faStar,
    faGithub,
    faChevronRight,
    faCode,
    faAtom,
    faBoxArchive,
    faCloudShowersHeavy,
    faFlag,
    faChevronLeft,
    faSpinner,
    faBtc,
    faWrench,
);
