nav:
    - predoc:
            - UserGuide:
                        - mainStructure
                        - websiteGuide
            - markdown_analysis:
                        - markdown-it
                        - MarkdownInterfaces
            - cache:
                    - GlobalInterfaces
                    - ConventionInterfaces
            - entry:
                    - EntryClass
                    - EntryTypes
            - component:
                        - PluginOptions
    - Misc: 
            - CustomGrammer
    - CS_related:
            - Cryptography:
                  - lec1
                  - lec2
                  - lec3
                  - lec4
                  - lec5
    - Tools
    - 数理:
        - 电工电子学及实验: 
                - lec1
                - lec2
                - lec3
                - lec4
                - lec5
icon:
    predoc: code
    Misc: github
    CS_related: flag
    数理: flag
#     Tools: wrench
